#!/bin/bash

# echo -n "what is the name of the project?"
# read -e PROJECT

# #setting up bower dependencies directory
# echo 'going to create bowerrc file'
# printf '%s\n' ' { "directory": "resources/assets/bower" }' > .bowerrc
# echo 'creating bower.json file'
# printf '%s\n \t%s %s %s %s\n' '{' '"name": "'"$PROJECT"'"' '}' > bower.json
# echo 'installing bower dependencies'
# bower install foundation -S foundation-icon-fonts -S react Project-OSRM/osrm-frontend-v2 -S
# 
# #install npm modules
# echo 'now installing npm packages'
# npm install --save-dev gulp-autoprefixer gulp-browserify gulp-cache gulp-compass gulp-concat gulp-livereload gulp-minify-css gulp-notify gulp-phpunit gulp-react gulp-rename gulp-ruby-sass gulp-uglify gulp-util tiny-lr
# 
# 
# #install jeffrey ways generators
# echo "installing jeffrey ways generators. Dont forget to update service providers'
# 
# composer require laracasts/generators --dev
# #initializing git
# #echo "# toibuonban5" >> README.md
# echo 'Initializing git repository'
# git init
# printf '%s\n %s\n %s\n %s\n' '/public/packages/vendor' 'node_modules/' '.sass-cache/' '/public/js/react/.module-cache' >> .gitignore
# git add .
# git commit -m "first commit"
# git remote add origin git@github.com:BryantDavidDavis/$PROJECT.git
# git push -u origin master

#installed testdummy from laravel, but then had to manually composer install Faker dev-master to get password option to work